[package]
name = "apc-mini"
version = "0.1.0"
authors = ["Kyle Strohbeck <kstrohbeck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
midir = "0.7.0"
